# Generated by Django 2.0.6 on 2018-06-30 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_task_completed', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['due_date'],
                'abstract': False,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_task_completed', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['due_date'],
                'abstract': False,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='api.Task'),
        ),
    ]
