# Generated by Django 2.0.6 on 2018-06-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='is_trashed',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_trashed',
            new_name='is_deleted',
        ),
    ]
