# Generated by Django 2.0.6 on 2018-06-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180630_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={},
        ),
        migrations.AlterModelManagers(
            name='subtask',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('title', 'parent_task')},
        ),
    ]
